version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-container
    ports:
      - 27017:27017
    volumes:
      - mongoData:/data/db
    networks:
      - movie_net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - 3000:3000
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    networks:
      - movie_net
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-frontend
    depends_on:
      - mongo
      - backend
    ports:
      - 8000:8000
    networks:
      - movie_net
    volumes:
      - ./frontend:/app
      - frontend_module:/app/node_modules


networks:
  movie_net:
    driver: bridge

volumes:
  mongoData:  
  frontend_module: 

